'use strict';
let state, mode='v2development', selectedEvent=null, selectedCell=1, timer, lastJob='';
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=1)=>v==null?'—':Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const money=v=>(v<0?'−$':'$')+n(Math.abs(v),2), bps=v=>v==null?'—':(v>0?'+':'')+n(v*10000,1), pct=v=>v==null?'—':n(v*100,2)+'%';
const sign=v=>v==null?'':v<0?'negative':'positive';
const empty=s=>`<div class="empty-state"><strong>No result yet</strong>${esc(s)}</div>`;
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='show'+(error?' error':'');clearTimeout(timer);timer=setTimeout(()=>el.className='',6500)}
async function api(path,body){if(window.FILING_REPLAY)return window.replayRequest(path,body);const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Filing-Edge':'1'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw Error(result.error||'Request failed');return result}
async function refresh(){state=await api('state');render();}
async function job(action,body={}){try{await api(action,body);toast('Started '+action+'. Progress appears at the bottom of the page.');await refresh()}catch(e){toast(e.message,true)}}
function changeView(view){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===view));document.querySelectorAll('.nav').forEach(el=>el.classList.toggle('active',el.dataset.view===view));history.replaceState(null,'','#'+view);window.scrollTo(0,0);if(view==='capital'&&!$('#capitalResult').innerHTML)capital();}
function metric(label,value,note,klass=''){return `<div class="metric"><div class="metric-label">${label}</div><div class="metric-value ${klass}">${value}</div><div class="metric-note">${note}</div></div>`}
function render(){
 const report=state.reports[mode], cov=state.coverage_windows?.[mode]||state.coverage, running=state.job.status==='running';
 document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));
 $('#runStudy').textContent=mode==='synthetic'&&!window.FILING_REPLAY?'Rebuild synthetic demo →':'Refresh results ↻';
 $('#holdoutStatus').textContent=state.holdout;
 const gate=state.readiness?.[mode];$('#readiness').innerHTML=gate?'<div class="readiness-grid">'+gate.checks.map(c=>'<div class="integrity-row"><span class="'+(c.passed?'positive':'negative')+'">'+(c.passed?'✓':'×')+'</span><div><strong>'+esc(c.name)+'</strong><small>'+esc(c.detail)+'</small></div></div>').join('')+'</div><p class="subtle">'+esc(gate.note)+'</p>':'<p class="subtle">A completed report is needed for the review checklist.</p>';
 $('#period').textContent=mode==='v2test'?'Held-out test · Jan–Aug 2026':'Development · 2024–2025';
 document.querySelectorAll('[data-job],#syncDatabase').forEach(b=>b.disabled=running||!!window.FILING_REPLAY);$('#runStudy').disabled=running;
 $('#jobStatus').textContent=state.job.message;
 if(state.job.status==='failed'&&lastJob!==state.job.finished_at)toast(state.job.message,true);
 if(state.job.status==='complete'&&lastJob!==state.job.finished_at)toast(state.job.message);
 lastJob=state.job.finished_at||lastJob;
 $('#provenance').className='notice'+(mode==='massive'?' market':'');
 $('#provenance').textContent=mode==='synthetic'?'SYNTHETIC DEMONSTRATION · Fabricated prices demonstrate the software. These numbers are not evidence of a trading edge.':report?'DEVELOPMENT PILOT · Historical daily-trade-price proxies, not executable quotes. Research conclusions remain provisional; missing pairs are excluded.':'COVERAGE VERIFIED · Market performance has not been evaluated. Freeze the pilot specification, then run the development study. The 2026 holdout stays locked.';
 if(mode.startsWith('v2'))$('#provenance').textContent=report?'VERSION 2 · Historical NBBO simulation. Selling uses the bid, buying uses the ask, with fees and adverse haircuts. No live orders.':'This frozen study is being prepared. Missing results are not a zero return. The original pilot and synthetic software demo remain available.';
 const h=report?.horizons.find(x=>x.horizon===21)?.groups.standalone;
 $('#metrics').innerHTML=metric('Incremental net return',bps(h?.edge)+'<small>bps</small>','21 sessions · event minus control',sign(h?.edge))+metric('Complete matched pairs',n(h?.pairs,0),'Same issuer · full strike collateral')+metric('Issuers in comparison',n(h?.issuers,0),'Repeated events are clustered')+metric('95% exploratory interval',h?.interval?`${bps(h.interval[0])} / ${bps(h.interval[1])}`:'—','bps · issuer / quarter envelope','interval');
 heatmap(report);horizonChart(report);
 $('#coverageSummary').innerHTML=cov?`<div class="coverage-stats"><div><strong>${cov.filings}</strong><span>Qualifying filings</span></div><div><strong>${cov.issuers}</strong><span>Issuers</span></div><div><strong>${cov.context_counts.adverse||0}</strong><span>With adverse tags</span></div></div><p class="subtle">${cov.context_counts.adverse?'Context groups available for inspection.':'No adverse-tag matches. The adverse-context comparison is untestable in this coverage sample.'} Filing labels can be retrospective.</p>`:empty('Collect the development filing coverage first.');
 $('#integrity').innerHTML=[['✓','Versioned research',mode.startsWith('v2')?'Original development findings disclosed before this revision.':'Archived daily-price pilot; not the final method.'],['▣',state.freeze_v2?'Version 2 method frozen':'Awaiting final freeze',state.freeze_v2?'Source '+state.freeze_v2.source_hash.slice(0,12):'No test conclusion yet.'],['▣',state.holdout,'One fixed primary hypothesis; every sensitivity is reported.'],['↗',report?'Run '+report.run_id.slice(0,10):'No completed run for this window',report?'Data hash '+report.data_hash.slice(0,12):'Do not infer a result from an empty chart.']].map(x=>`<div class="integrity-row"><span>${x[0]}</span><div><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></div></div>`).join('');
 $('#ledgerCount').textContent=report?.published_summary?'RAW LEDGER IN AUTHENTICATED APP':report?report.trades.length+' priced event observations':'NO MARKET RESULTS';
 $('#ledger').innerHTML=report?.trades.length?report.trades.map(t=>`<tr><td>${esc(t.ticker)}</td><td>${esc(t.entry)} → ${esc(t.exit)}</td><td>${money(t.strike)}</td><td>${money(t.entry_mark)} / ${money(t.exit_mark)}</td><td>${money(t.costs)}</td><td class="${sign(t.net_pnl)}">${money(t.net_pnl)}</td><td class="${sign(t.net_return)}">${pct(t.net_return)}</td></tr>`).join(''):'<tr><td colspan="7">'+(report?.published_summary?'Raw option quotes are excluded from the public replay. Run the authenticated app or judge notebook to inspect individual trade accounting.':'No priced observations for this source. Missing prices are never carried forward.')+'</td></tr>';
 $('#warnings').innerHTML=(report?.warnings||['No market-return conclusion has been produced.']).map(w=>'<p>'+esc(w)+'</p>').join('')+(report?'<p>Excluded headline observations: '+esc(JSON.stringify(report.horizons.find(x=>x.horizon===21)?.unavailable))+'</p>':'');
 renderFilings();renderProviders();renderPortfolio(report);renderAudio(state.audio?.run_id===report?.run_id?state.audio:null);
}
function heatmap(report){if(!report){$('#heatmap').innerHTML=empty('A cost-and-delay map appears after evaluation. Switch to the synthetic demo to explore the interface.');$('#cellDetail').textContent='Every requested scenario is reported. We do not select the best cell.';return;}
 let html='<div class="heatmap"><div class="heat-head">ENTRY DELAY ↓</div>'+state.config.haircuts.map(h=>`<div class="heat-head">${n(h*100,1)}% haircut</div>`).join('');
 state.config.delays.forEach(d=>{html+=`<div class="heat-axis">${d} session${d>1?'s':''}</div>`;report.grid.filter(c=>c.delay===d).forEach(c=>{const i=report.grid.indexOf(c);html+=`<button class="cell ${c.edge==null?'empty':sign(c.edge)} ${i===selectedCell?'active':''}" data-cell="${i}" aria-label="${d} session delay, ${n(c.haircut*100)} percent haircut, ${bps(c.edge)} basis points">${bps(c.edge)}<small>${c.pairs} pairs</small></button>`})});$('#heatmap').innerHTML=html+'</div>';cellDetail(report);}
function cellDetail(report){const c=report.grid[selectedCell]||report.grid[0];$('#cellDetail').innerHTML=`<strong>${c.delay}-session delay · ${n(c.haircut*100,1)}% haircut per premium leg</strong><br>Event ${pct(c.event_return)} · Control ${pct(c.control_return)}<br>${c.pairs} pairs · ${c.issuers} issuers · Interval ${c.interval?bps(c.interval[0])+' to '+bps(c.interval[1])+' bps':'unavailable'} · ${esc(c.status)}`;}
function horizonChart(report){if(!report){$('#horizonChart').innerHTML=empty('All fixed horizons will appear here, including failures and missing observations.');return;}
 const hs=report.horizons;const values=hs.flatMap(h=>Object.values(h.groups).flatMap(g=>g.edge==null?[]:[g.edge,...(g.interval||[])]));let lo=Math.min(0,...values),hi=Math.max(.0001,...values);const pad=(hi-lo)*.15;lo-=pad;hi+=pad;const w=490,h=250,left=55,right=465,top=20,bottom=205,x=i=>left+i*(right-left)/(hs.length-1),y=v=>bottom-(v-lo)/(hi-lo)*(bottom-top);
 let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Incremental returns and exploratory intervals across all fixed horizons">`;
 for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3;svg+=`<line class="grid" x1="${left}" y1="${y(v)}" x2="${right}" y2="${y(v)}"/><text x="${left-10}" y="${y(v)+3}" text-anchor="end">${n(v*10000,0)}</text>`}
 svg+=`<line class="zero" x1="${left}" y1="${y(0)}" x2="${right}" y2="${y(0)}"/><text x="10" y="12">bps</text>`;
 for(const context of ['standalone','adverse']){let points=[];hs.forEach((v,i)=>{const g=v.groups[context];if(g.edge==null){if(points.length)svg+=`<polyline class="line ${context}" points="${points.join(' ')}"/>`;points=[];return;}points.push(`${x(i)},${y(g.edge)}`);if(g.interval)svg+=`<line class="band" x1="${x(i)}" y1="${y(g.interval[0])}" x2="${x(i)}" y2="${y(g.interval[1])}"/>`;svg+=`<circle class="${context}" cx="${x(i)}" cy="${y(g.edge)}" r="4"><title>${esc(context)} · ${v.horizon} sessions: ${bps(g.edge)} bps · ${g.pairs} pairs</title></circle>`});if(points.length)svg+=`<polyline class="line ${context}" points="${points.join(' ')}"/>`;}
 hs.forEach((v,i)=>svg+=`<text x="${x(i)}" y="230" text-anchor="middle">${esc(v.horizon)}</text>`);$('#horizonChart').innerHTML=svg+'</svg>';}
function renderFilings(){const events=state.coverage?.events||[],q=$('#filingSearch').value.toLowerCase();if(!selectedEvent&&events.length)selectedEvent=events[0].id;
 const filtered=events.filter(e=>(e.ticker+' '+e.tags.join(' ')).toLowerCase().includes(q));$('#filingList').innerHTML=filtered.length?filtered.map(e=>`<button class="filing-item ${e.id===selectedEvent?'selected':''}" data-event="${esc(e.id)}"><span>${esc(e.ticker)}<small>${esc(e.filing_date)}</small></span><span>↗</span></button>`).join(''):empty('No matching filings.');
 const e=events.find(e=>e.id===selectedEvent);if(!e){$('#filingDetail').innerHTML=empty('Run coverage to load source excerpts.');return;}
 if($('#filingDetail').dataset.event===e.id)return;
 $('#filingDetail').dataset.event=e.id;
 const safeLink=/^https:\/\/(www\.)?sec\.gov\//.test(e.source_url);
 $('#filingDetail').innerHTML=`<div class="panel-heading"><div><div class="eyebrow">FORM 8-K / ${esc(e.id)}</div><h2 class="filing-title">${esc(e.ticker)} · Share repurchase</h2></div>${safeLink?`<a class="text-button" href="${esc(e.source_url)}" target="_blank" rel="noopener noreferrer">SEC source ↗</a>`:''}</div><p class="subtle">${e.context==='adverse'?'Predefined adverse co-disclosure present.':'No predefined adverse tag found. This does not establish that the news is favorable.'}</p><div class="timeline"><div><span>FILING DATE</span><strong>${esc(e.filing_date)}</strong></div><div><span>SESSION ANCHOR</span><strong>${esc(e.anchor)}</strong></div><div><span>ASSUMED TAG AVAILABILITY</span><strong>${esc(e.available)}</strong></div></div><div>${e.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>${e.disclosures.map(d=>`<div class="disclosure-label">${esc(d.category)}</div><blockquote>${esc(d.text||'No source excerpt available.')}</blockquote>`).join('')}<div class="explanation"><div class="panel-heading"><h2>Ask the evidence</h2><button class="primary" id="explain">Explain with Gemini →</button></div><p class="subtle">Only these excerpts are sent to Gemini. Every quoted span must match the source; explanations never affect research signals.</p><div id="explanation"></div></div>`;}
function renderProviders(){$('#providers').innerHTML=state.connections.map(p=>`<article class="panel"><div class="provider-title"><h2>${esc(p.name)}</h2><span class="status ${p.status==='connected'?'connected':''}">● ${esc(p.status)}</span></div><p class="purpose">${esc(p.purpose)}</p><p>${esc(p.detail||'Configure this provider in the private .env file.')}</p><small class="subtle">${p.checked_at?'Checked '+esc(new Date(p.checked_at).toLocaleString()):'No access check yet'}</small></article>`).join('');const db=state.database;$('#database').innerHTML=db?'<div class="db-summary">'+['massive','synthetic'].map(k=>`<div><strong>${n(db.contract_sessions[k]||0,0)}</strong><small>${k==='massive'?'Market':'Synthetic'} contract sessions</small></div><div><strong>${n(db.daily_buckets[k]||0,0)}</strong><small>${k==='massive'?'Market':'Synthetic'} daily aggregates</small></div>`).join('')+'</div>':'<p class="subtle">No saved table verification yet. Initialize once, then synchronize a study.</p>';}
async function capital(){try{const form=new FormData($('#capitalForm'));const input=Object.fromEntries([...form].map(([k,v])=>[k,Number(v)]));input.allocation/=100;const r=await api('capital',input);$('#capitalResult').innerHTML=`<div class="capital-metrics"><div><span>Contracts</span><strong>${r.contracts}</strong></div><div><span>Reserved collateral</span><strong>$${n(r.collateral,0)}</strong></div><div><span>Maximum loss</span><strong class="negative">$${n(r.max_loss,0)}</strong></div></div><p class="subtle">Premium received ${money(r.premium_received)} · Break-even ${money(r.breakeven)} per share</p><div class="table-wrap"><table><thead><tr><th>Stock move</th><th>Stock at expiry</th><th>Position P&L</th><th>Account return</th></tr></thead><tbody>${r.scenarios.map(s=>`<tr><td>${n(s.move*100,0)}%</td><td>${money(s.terminal)}</td><td class="${sign(s.pnl)}">${money(s.pnl)}</td><td class="${sign(s.pnl)}">${pct(s.account_return)}</td></tr>`).join('')}</tbody></table></div><p class="subtle">${esc(r.note)}</p>`}catch(e){toast(e.message,true)}}
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;
 if(b.dataset.view)return changeView(b.dataset.view);
 if(b.dataset.mode){mode=b.dataset.mode;render();return;}
 if(b.dataset.job)return job(b.dataset.job);
 if(b.dataset.cell!==undefined){selectedCell=Number(b.dataset.cell);heatmap(state.reports[mode]);return;}
 if(b.dataset.event){selectedEvent=b.dataset.event;renderFilings();return;}
 if(b.id==='runStudy')return mode==='synthetic'&&!window.FILING_REPLAY?job('demo'):refresh();
 if(b.id==='makeBriefing'){b.disabled=true;try{const r=await api('briefing',{kind:mode});state.audio=r;renderAudio(r)}catch(e){toast(e.message,true)}finally{b.disabled=false}return;}
 if(b.id==='loadDatabase'){b.disabled=true;try{const r=await api('database');$('#databaseLive').innerHTML='<p>'+esc(r.source)+' · '+r.daily.length+' recent trading days</p><div class="table-wrap"><table><thead><tr><th>Day</th><th>Contract series</th><th>Option volume</th></tr></thead><tbody>'+r.daily.slice(-12).map(x=>'<tr><td>'+esc(x.day)+'</td><td>'+n(x.contracts,0)+'</td><td>'+n(x.volume,0)+'</td></tr>').join('')+'</tbody></table></div><p>'+r.runs.length+' saved research runs returned by PostgreSQL.</p>'}catch(e){toast(e.message,true)}finally{b.disabled=false}return;}
 if(b.id==='syncDatabase')return job('database-sync',{kind:mode.startsWith('v2')?'massive':mode});
 if(b.id==='export'){if(!state.reports[mode])return toast('Run this study before exporting.',true);if(window.FILING_REPLAY){const u=URL.createObjectURL(new Blob([JSON.stringify(state.reports[mode],null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='filing-edge-'+mode+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}else location.href='/api/report?kind='+mode;return;}
 if(b.id==='explain'){b.disabled=true;$('#explanation').textContent='Reading the supplied excerpts…';try{const r=await api('explain',{id:selectedEvent});$('#explanation').innerHTML=`<p>${esc(r.summary)}</p>${r.claims.map(c=>`<p>${esc(c.claim)}</p><blockquote>${esc(c.quote)}</blockquote>`).join('')}<p class="subtle">${r.limitations.map(esc).join(' · ')}</p><p class="subtle">${esc(r.basis)} · ${esc(r.model)}</p>`}catch(e){$('#explanation').textContent=e.message;toast(e.message,true)}finally{b.disabled=false}}
});
$('#filingSearch').addEventListener('input',renderFilings);$('#capitalForm').addEventListener('submit',e=>{e.preventDefault();capital()});
refresh().then(()=>changeView(['research','evidence','capital','connections'].includes(location.hash.slice(1))?location.hash.slice(1):'research')).catch(e=>toast(e.message,true));
setInterval(()=>{if(state?.job.status==='running')refresh().catch(e=>toast(e.message,true))},2000);

function renderAudio(a){$('#audioBriefing').innerHTML=a?`<audio controls preload="none" src="${esc(a.url)}"></audio><details><summary>Read the exact transcript</summary><p>${esc(a.transcript)}</p></details>`:'<p class="subtle">Generate the briefing for the selected completed report.</p>';}
function renderPortfolio(report){const p=report?.portfolio;$('#portfolioPanel').hidden=!p;if(!p)return;
 $('#portfolioMetrics').innerHTML='<div class="metrics">'+metric('Account return',pct(p.total_return),'Includes idle cash earning zero')+metric('Annualized return',pct(p.cagr),'CAGR over the full window')+metric('Annualized volatility',pct(p.annualized_volatility),'Daily account returns')+metric('Worst drawdown',pct(p.max_drawdown),'Decline from the prior account peak')+'</div>';
 const c=p.curve,lo=Math.min(p.initial_capital,...c.map(x=>x.equity)),hi=Math.max(p.initial_capital+1,...c.map(x=>x.equity)),w=960,h=200;
 $('#equityCurve').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Simulated account equity with conservative reserves for missing marks"><text x="8" y="20">$${n(hi,0)}</text><text x="8" y="180">$${n(lo,0)}</text><polyline class="equity-line" points="${c.map((x,i)=>(100+i*840/Math.max(1,c.length-1))+','+(170-(x.equity-lo)/Math.max(1,hi-lo)*140)).join(' ')}"/><text x="100" y="196">${esc(c[0]?.day)}</text><text x="840" y="196">${esc(c.at(-1)?.day)}</text></svg>`;
 $('#portfolioDetail').innerHTML=`<p><strong>${p.trade_count} positions admitted</strong> · ${p.closed_positions} closed · ${p.open_positions} still reserved · Sharpe (zero cash benchmark) ${n(p.sharpe_zero_cash,2)} · Premium cash turnover ${n(p.premium_cash_turnover_per_year,3)}×/year</p><p>${p.stale_mark_days} days used conservative missing-price reserves. ${p.drawdown_paused?'New entries paused after the drawdown limit.':'Drawdown pause was not triggered.'}</p><details><summary>See capacity exclusions and accounting limits</summary><p>${Object.entries(p.skipped).map(([k,v])=>esc(k.replaceAll('_',' '))+': '+v).join(' · ')}</p>${p.limitations.map(x=>'<p>'+esc(x)+'</p>').join('')}</details>`;
}
